services:
  app:
    container_name: metatool-app
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    env_file:
      - .env
    restart: always
    ports:
      - "12005:12005"
    environment:
      - NODE_ENV=production
      # Ensure the Next.js app inside Docker knows which port to listen on
      - PORT=12005
      # Environment variables for the new /config route
      - REMOTE_HOSTING_ENV=docker
      - REMOTE_HOSTING_ARGS= # Add any specific args if needed
      # For Sub-MCP server executed by createMetaMcpTransport
      - METAMCP_API_BASE_URL=http://localhost:12005
      - USE_DOCKER_HOST=false # Since we are in the same network, direct host is fine
      # DATABASE_URL can be set in .env file if needed, e.g. DATABASE_URL=sqlite.db
      # Or rely on the default 'sqlite.db' in db/index.ts
    extra_hosts:
      - "host.docker.internal:host-gateway"

# No external volumes needed for SQLite by default
# If you want to persist sqlite.db outside the container, you could add a volume mount here:
# volumes:
#   metatool_db_data:
# And in app service:
#   volumes:
#     - metatool_db_data:/app/sqlite.db # Assuming sqlite.db is in /app
