services:
  app:
    container_name: metatool-app
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    # env_file removed
    restart: always
    ports:
      - "12005:12005"
    environment:
      - NODE_ENV=production
      # Ensure the Next.js app inside Docker knows which port to listen on
      - PORT=12005
      # DATABASE_URL can be set here if needed, e.g. DATABASE_URL=sqlite.db
      # Or rely on the default 'sqlite.db' in db/index.ts
      # Public environment variables for Next.js (available client & server side)
      # These are typically set at build time, but can be overridden at runtime if app is configured for it.
      # For server-side use of these, they must be explicitly passed.
      - NEXT_PUBLIC_APP_URL=http://localhost:12005
      - NEXT_PUBLIC_REMOTE_HOSTING_URL=/ # Changed to relative path
    extra_hosts:
      - "host.docker.internal:host-gateway"

# No external volumes needed for SQLite by default
# If you want to persist sqlite.db outside the container, you could add a volume mount here:
# volumes:
#   metatool_db_data:
# And in app service:
#   volumes:
#     - metatool_db_data:/app/sqlite.db # Assuming sqlite.db is in /app
