services:
  app:
    container_name: metatool-app
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    restart: always
    ports:
      - "12005:12005"
    environment:
      - NODE_ENV=production
      - PORT=12005
      - NEXT_PUBLIC_APP_URL=http://localhost:12005
      - NEXT_PUBLIC_REMOTE_HOSTING_URL=/
      - DATABASE_URL=/app/data/sqlite.db # Set the database path to the mounted volume
      - COREPACK_HOME=/tmp/corepack # Set corepack home to a writable directory
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - metatool_db_data:/app/data # Mount the volume to a directory

volumes:
  metatool_db_data: