name: Build and Publish Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push metatool-web image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          target: runner
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/metatool-web:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/metatool-web:${{ github.sha }}

      - name: Build and push metatool-remote-hosting image
        uses: docker/build-push-action@v5
        with:
          context: ./remote-hosting
          file: ./remote-hosting/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/metatool-remote-hosting:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/metatool-remote-hosting:${{ github.sha }}

      - name: Build and push metatool-migrator image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          target: migrator
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/metatool-migrator:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/metatool-migrator:${{ github.sha }}

      - name: Build and push metatool-nginx image
        uses: docker/build-push-action@v5
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/metatool-nginx:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/metatool-nginx:${{ github.sha }}

